os: linux
notifications:
  email: false
dist: xenial
language: python
python:
  - "3.6"
env:
  - JAX_ENABLE_X64=0 JAX_NUM_GENERATED_CASES=25
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
  - conda config --set channel_priority strict
  - conda config --set add_pip_as_python_dependency yes
  - conda config --remove channels defaults
  - conda config --add channels conda-forge
  - conda update -q conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip absl-py opt_einsum numpy scipy pytest-xdist pytest-benchmark
  - pip install jaxlib jax
  - pip install tensorflow tensorflow-datasets
  - pip install -v .
  - pip install -r docs/requirements.txt
  # pandoc is needed to build notebooks in docs
  - conda install -c conda-forge pandoc
script:
  # build the docs
  - sphinx-build -M html docs docs/_build
  - tests/run_all_tests.sh
